version: '3'

services:
  odyssey:
    build:
      dockerfile: ./docker-test/Dockerfile
      context: .
    environment:
      CMAKE_BUILD_TYPE: "${CMAKE_BUILD_TYPE:-Debug}"
    ports:
      - "6432:6432"
    volumes:
      - ./odyssey.conf:/etc/odyssey.conf
      - ..:/odyssey
